// import "./globals.css";

export const metadata = {
  title: "Blog detail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
